### ISSUE TITLE
Plugin fails to load

### ISSUE THREAD

**Issue by lmaobamar** [3arthqu4ke/phobot#28]
`Failed to load plugin pingbypass\plugins\phobot-1.20.4-0.1.0.jar
java.lang.NullPointerException: entry
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at java.base/java.util.zip.ZipFile.getInputStream(ZipFile.java:361)
	at java.base/java.util.jar.JarFile.getInputStream(JarFile.java:853)
	at me.earth.pingbypass.api.launch.PluginDiscoveryServiceImpl.readJar(PluginDiscoveryServiceImpl.java:95)
	at me.earth.pingbypass.api.launch.PluginDiscoveryServiceImpl.lambda$checkDirectory$0(PluginDiscoveryServiceImpl.java:75)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at me.earth.pingbypass.api.launch.PluginDiscoveryServiceImpl.checkDirectory(PluginDiscoveryServiceImpl.java:73)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at me.earth.pingbypass.api.launch.PluginDiscoveryServiceImpl.load(PluginDiscoveryServiceImpl.java:40)
	at me.earth.pingbypass.api.launch.SideLaunchingPlugin.<init>(SideLaunchingPlugin.java:29)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:97)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`

**Comment by 3arthqu4ke** [comment]
You need the phobot-1.20.4-0.1.0-fabric or phobot-1.20.4-0.1.0-lexforge or phobot-1.20.4-0.1.0-neoforge jar
not the phobot-1.20.4-0.1.0.jar

**Comment by lmaobamar** [comment]
Got it, will try

**Comment by lmaobamar** [comment]
Now it doesn't complain about loading the plugin, but I can't actually enable Phobot or any of its modules. I can't even use the + prefix in chat
